name: terraform

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: GitHub
    name: innovationnorway/azure-pipelines-yaml

trigger:
- master

# pr:
# - master
    
jobs:

- job: fmt
  steps:
  - template: terraform/fmt.yml@templates

- job: init
  dependsOn: fmt
  condition: succeeded()
  steps:
  - template: terraform/init.yml@templates

- job: validate
  dependsOn: init
  condition: succeeded()
  steps:
  - template: terraform/validate.yml@templates
  
- job: plan
  dependsOn: validate
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - template: terraform/plan.yml@templates

- job: apply
  dependsOn: plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - template: terraform/apply.yml@templates
